name: Slycot from source

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout python-control
      uses: actions/checkout@v3
      with:
        path: python-control
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Python dependencies
      run: |
        # Set up (virtual) X11
        sudo apt-get -y install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils

        # Install test tools
        pip install pytest pytest-timeout

        # Install python-control dependencies
        pip install numpy matplotlib scipy

    - name: Checkout Slycot
      uses: actions/checkout@v3
      with:
        repository: python-control/Slycot
        submodules: recursive
        fetch-depth: 0
        path: slycot
    - name: Install slycot from source
      env:
        BLA_VENDOR: Generic
        CMAKE_GENERATOR: Unix Makefiles
      working-directory: slycot
      run: |
        # Install compilers, libraries, and development environment
        sudo apt-get -y install gfortran cmake --fix-missing
        sudo apt-get -y install libblas-dev liblapack-dev

        # Compile and install slycot
        pip install -v .

    - name: Test with pytest
      working-directory: python-control
      run: xvfb-run pytest control/tests
